# Generated by Django 6.0.4 on 2026-04-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='causes',
            old_name='image_url',
            new_name='image',
        ),
    ]
