# Generated by Django 6.0.4 on 2026-04-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_image_url_causes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='causes',
            old_name='image',
            new_name='image_url',
        ),
    ]
