# Generated by Django 6.0.4 on 2026-04-20 16:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_image_causes_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='receipt_pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cause_receipts/'),
        ),
    ]
